In [1]:
from tensorflow.keras.datasets import reuters
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding,Flatten
from tensorflow.keras.utils import to_categorical as to_cat
import numpy as np ; import matplotlib.pyplot as plt
#import cv2,os 
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [3]:
(x_train,y_train) ,(x_test,y_test) =  reuters.load_data(num_words=10000)

In [5]:
print(x_train[0][:5])
print(x_train.shape,y_train.shape)

[1, 2, 2, 8, 43]
(8982,) (8982,)


In [6]:
print(len(x_train[6]), len(x_train[5]))
np.unique(np.array(y_train))

100 116


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45], dtype=int64)

In [8]:
def vectorize_sequences(sequences,dimensions=10000):
    results =  np.zeros((len(sequences),dimensions))

    for (i ,sequence) in enumerate(sequences):
        for j in sequence:
            results[i, j]  =  1 
    return results
        

In [9]:
x_train_vector = vectorize_sequences(x_train)
x_test_vector =  vectorize_sequences(x_test)
x_train_vector[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [33]:
x_train_vector.shape

(8982, 10000)

In [10]:
y_train_cat = to_cat(y_train)
y_test_cat =  to_cat(y_test)
y_train_cat.shape

(8982, 46)

In [36]:
model = Sequential([
    Dense(64,activation="relu"),
    Dense(64,activation="relu"),
    Dense(46,activation="softmax")
])
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["acc"])
model.fit(x_train_vector,y_train_cat,validation_data=(x_test_vector,y_test_cat),epochs=10)

Epoch 1/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 7s 17ms/step - acc: 0.5517 - loss: 2.0949 - val_acc: 0.7636 - val_loss: 1.0429
Epoch 2/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - acc: 0.8460 - loss: 0.6804 - val_acc: 0.7956 - val_loss: 0.9188
Epoch 3/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - acc: 0.9347 - loss: 0.3169 - val_acc: 0.7992 - val_loss: 0.9376
Epoch 4/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - acc: 0.9522 - loss: 0.2238 - val_acc: 0.7992 - val_loss: 0.9603
Epoch 5/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - acc: 0.9549 - loss: 0.1699 - val_acc: 0.7930 - val_loss: 1.0132
Epoch 6/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - acc: 0.9566 - loss: 0.1535 - val_acc: 0.7934 - val_loss: 1.0019
Epoch 7/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - acc: 0.9609 - loss: 0.1364 - val_acc: 0.7970 - val_loss: 0.9949
Epoch 8/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - acc: 0.9551 - loss: 0.1433 - val_acc: 0.7916 - val_loss: 1.0530
Epoch 9/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/

In [38]:
loss,acc = model.evaluate(x_test_vector,y_test_cat)
acc

71/71 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - acc: 0.8071 - loss: 1.0285


0.7960819005966187

Model has 79% ACC on test set 

In [39]:
del model

In [55]:
num_words =  10000
maxlen = 100
pad_type= "post"
trunc_type="post"
#embed_dim =  128

In [44]:
token  = Tokenizer(num_words=num_words)
token.fit_on_sequences(x_train)

In [45]:
x_train_ =  token.sequences_to_matrix(x_train)
x_test_ =  token.sequences_to_matrix(x_test)
x_train_[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [48]:
x_train_padded =  pad_sequences(x_train_,padding=pad_type,truncating=trunc_type,maxlen=maxlen)
x_test_padded =  pad_sequences(x_test_,padding=pad_type,truncating=trunc_type,maxlen=maxlen)

In [56]:
x_test_padded.shape

(2246, 100)

In [53]:
model = Sequential([
    Embedding(input_dim=num_words,output_dim=150,input_length=maxlen),
    Flatten(),
    Dense(64,activation="relu"),
    Dense(64,activation="relu"),
    Dense(46,activation="softmax")
])
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["acc"])
history  = model.fit(x_train_padded,y_train_cat,validation_data=(x_test_padded,y_test_cat),epochs=10)

Epoch 1/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - acc: 0.5041 - loss: 2.0894 - val_acc: 0.6411 - val_loss: 1.4827
Epoch 2/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - acc: 0.6679 - loss: 1.3708 - val_acc: 0.6625 - val_loss: 1.3812
Epoch 3/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - acc: 0.6887 - loss: 1.2508 - val_acc: 0.6670 - val_loss: 1.3595
Epoch 4/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - acc: 0.7081 - loss: 1.1558 - val_acc: 0.6790 - val_loss: 1.3369
Epoch 5/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - acc: 0.7260 - loss: 1.0724 - val_acc: 0.6781 - val_loss: 1.3191
Epoch 6/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - acc: 0.7331 - loss: 1.0445 - val_acc: 0.6736 - val_loss: 1.3509
Epoch 7/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - acc: 0.7438 - loss: 0.9986 - val_acc: 0.6834 - val_loss: 1.3371
Epoch 8/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - acc: 0.7408 - loss: 0.9914 - val_acc: 0.6790 - val_loss: 1.3472
Epoch 9/10
281/281 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/

In [54]:
loss,acc = model.evaluate(x_test_padded,y_test_cat)
acc

71/71 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.6597 - loss: 1.4551


0.6678539514541626

Model has 66% acc on test set 