In [55]:
import numpy as np 
import pandas as pd 

from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split 
from sklearn.metrics import r2_score

In [2]:
x,y = load_diabetes(return_X_y=True)

In [3]:
x_train,x_test,y_train,y_test =  train_test_split(x,y)

In [4]:
x_train.shape,y_train.shape

((331, 10), (331,))

### Most imp  thing to notice 
=>  if you see mathemtaical formulation then you  will notice that first value of every row is 1  <br />
=>  we need to implement that same 

## MODELS

### My model 

In [54]:
class MultipleLR :
    def fit(self,x,y):
        x = np.insert(x,0,1,axis=1) # putting values 1 in very first column columnwise 
        beta_matrix  =  np.linalg.inv(np.dot(x.T,x)).dot(x.T).dot(y)
        self.coef_ =  beta_matrix[1:]
        self.intercept_  = beta_matrix[0]
        self.beta_matrix =  beta_matrix
    def predict(self,x_test):
        #x_test = np.squeeze(np.asarray(x_test))
        # in source there is x_test not x_test.T so adjust if it works or not 
        y_hat =  np.dot(self.coef_,x_test.T)  +  self.intercept_
        return y_hat

        

In [49]:
model = MultipleLR()
model.fit(x_train,y_train)
model.intercept_, model.coef_

(151.2624562539996,
 array([  -11.78902527,  -256.90665059,   459.59203106,   394.18712273,
        -1016.05245842,   569.12458825,   276.54131045,   311.75931378,
          823.06798047,    90.37008205]))

In [59]:
y_hat =  model.predict(x_test)
y_hat[:15]

array([199.60745042,  67.0770163 , 123.07823034, 235.09639194,
        99.28931329, 130.54765948, 172.94061696, 227.17633561,
       155.62576106, 214.04367335, 122.99503215, 107.29383382,
       144.57387134,  66.07826211, 215.5354894 ])

In [64]:
r2_score(y_test,y_hat)

0.4630765355127088

### SKLEARN MODEL

In [52]:
model_= LinearRegression()
model_.fit(x_train,y_train)
model_.coef_,model_.intercept_

(array([  -11.78902527,  -256.90665059,   459.59203106,   394.18712273,
        -1016.05245842,   569.12458825,   276.54131045,   311.75931378,
          823.06798047,    90.37008205]),
 151.26245625399963)

In [53]:
model_.predict(x_test)

array([199.60745042,  67.0770163 , 123.07823034, 235.09639194,
        99.28931329, 130.54765948, 172.94061696, 227.17633561,
       155.62576106, 214.04367335, 122.99503215, 107.29383382,
       144.57387134,  66.07826211, 215.5354894 ,  71.73829603,
       149.74719582, 102.35612755,  79.82694531, 138.46102182,
       162.89758517, 215.49065877, 196.70303149, 177.88087412,
       285.65653504,  35.32894346, 136.42006725,  80.16002078,
        60.91065407,  70.07298618, 147.23646825, 148.56667924,
       177.26050244, 163.89355727, 141.15639354, 164.99848697,
       178.99454369, 126.4242048 , 123.03380354,  81.12595661,
       132.20685755, 132.28795282,  99.5002833 , 200.06126911,
       160.7819767 , 170.0546013 , 202.5107534 , 134.5302556 ,
       162.19821987, 202.9210897 , 288.83294062,  72.24820457,
        55.33626988,  69.21212807,  66.66301823, 139.31015749,
        37.7943852 , 161.30200009, 193.79469838, 139.49002058,
       112.75058469,  56.25617455, 198.89212781, 187.34

In [61]:
y_predicted=  model_.predict(x_test)
y_predicted[:15]


array([199.60745042,  67.0770163 , 123.07823034, 235.09639194,
        99.28931329, 130.54765948, 172.94061696, 227.17633561,
       155.62576106, 214.04367335, 122.99503215, 107.29383382,
       144.57387134,  66.07826211, 215.5354894 ])

In [63]:
r2_score(y_test,y_predicted)

0.4630765355127088